
package com.lilith.webclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ServiceInterfaceService", targetNamespace = "http://webservice.lilith.com/", wsdlLocation = "http://localhost:8989/WS_Server/Webservice?wsdl")
public class ServiceInterfaceService
    extends Service
{

    private final static URL SERVICEINTERFACESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lilith.webclient.ServiceInterfaceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lilith.webclient.ServiceInterfaceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8989/WS_Server/Webservice?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8989/WS_Server/Webservice?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SERVICEINTERFACESERVICE_WSDL_LOCATION = url;
    }

    public ServiceInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceInterfaceService() {
        super(SERVICEINTERFACESERVICE_WSDL_LOCATION, new QName("http://webservice.lilith.com/", "ServiceInterfaceService"));
    }

    /**
     * 
     * @return
     *     returns ServiceInterface
     */
    @WebEndpoint(name = "ServiceInterfacePort")
    public ServiceInterface getServiceInterfacePort() {
        return super.getPort(new QName("http://webservice.lilith.com/", "ServiceInterfacePort"), ServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceInterface
     */
    @WebEndpoint(name = "ServiceInterfacePort")
    public ServiceInterface getServiceInterfacePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.lilith.com/", "ServiceInterfacePort"), ServiceInterface.class, features);
    }

}
